#version 460

#extension GL_EXT_scalar_block_layout : enable

struct Planet{
    //0-th is position at current time, 1-st is position at T+.5dt, 2-nd is position at T+dt
    dvec4 pos[3];
    dvec4 vel[3];
    dvec4 axis;
    dvec4 padding;
};
struct Satellite{
    dvec4 pos;
    dvec4 vel;
};
struct LineVertex{
    vec4 pos;
    vec4 base;
    vec4 inter;
    vec4 fin;
};
struct LineInfo{
    dvec4 pos;
    dvec4 vel;
    double relPos;
    double relVel;
    double tApproach;
    double score;
};


layout(constant_id = 0) const double G = 6.67e-11;
layout(constant_id = 1) const uint MAX_PLANETS_ARRAY_SIZE = 2;
layout(constant_id = 2) const uint SATELLITE_COUNT = 256;
layout(constant_id = 3) const uint LINE_VERTEX_COUNT = 1024;
layout(constant_id = 4) const uint COMPUTE_STEPS_PER_FRAME = 128;
layout(constant_id = 5) const uint MESH_STEPS_MAJOR = 16;
layout(constant_id = 6) const uint MESH_STEPS_MINOR = 8;
layout(constant_id = 7) const uint SATELLITES_PER_SHADER = 1;
layout(constant_id = 8) const uint STEPS_PER_SHADER = 1;
layout(constant_id = 9) const uint MESH_PER_SHADER = 1;

layout(binding = 0) readonly buffer UniformBufferObject{
    Planet planets[MAX_PLANETS_ARRAY_SIZE * COMPUTE_STEPS_PER_FRAME];
} ubo;

layout(binding = 1) readonly buffer inSSBO{
    Satellite inSats[SATELLITE_COUNT];
};
layout(binding = 2) buffer outSSBO{
    Satellite outSats[SATELLITE_COUNT];
};
layout(binding = 3) buffer lineSSBO{
    LineVertex vertices[SATELLITE_COUNT * LINE_VERTEX_COUNT];
};
layout(binding = 4) buffer lineInfoSSBO{
    LineInfo infos[SATELLITE_COUNT];
};
layout(binding = 5) buffer meshSSBO{
    LineVertex mesh[MESH_STEPS_MINOR * MESH_STEPS_MAJOR * 2];
};
layout(push_constant) uniform pc {
    double dt;
    uint pOffset;             
} constants;
layout(local_size_x = 1024) in;

void main(){
    
}